# Generated by Django 5.1.2 on 2026-01-07 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag', models.CharField(db_index=True, help_text='Unique RFID tag identifier', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Animal name', max_length=100)),
                ('species', models.CharField(blank=True, help_text='Animal species (e.g., Cow, Goat, Sheep)', max_length=50)),
                ('breed', models.CharField(blank=True, help_text='Animal breed', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, help_text='Animal date of birth', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFIDEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag', models.CharField(db_index=True, max_length=50)),
                ('reader_id', models.CharField(blank=True, help_text='RFID reader/gate identifier', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_events', to='sensors.animal')),
            ],
            options={
                'verbose_name': 'RFID Event',
                'verbose_name_plural': 'RFID Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag', models.CharField(db_index=True, help_text='RFID tag from ESP32', max_length=50)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Humidity in %', max_digits=5, null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in BPM', null=True)),
                ('spo2', models.IntegerField(blank=True, help_text='Blood oxygen level (SpO2) in %', null=True)),
                ('sensor_type', models.CharField(choices=[('TEMP', 'Temperature'), ('HUMID', 'Humidity'), ('HR', 'Heart Rate'), ('COMBINED', 'Combined Reading')], default='COMBINED', max_length=10)),
                ('device_id', models.CharField(blank=True, help_text='ESP32 device identifier', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='sensors.animal')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'rfid_tag'], name='sensors_sen_timesta_7ec5ab_idx'), models.Index(fields=['animal', '-timestamp'], name='sensors_sen_animal__85d73f_idx')],
            },
        ),
    ]
