# Generated by Django 5.1.2 on 2026-01-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='spo2',
        ),
    ]
